name: Build Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check Swift version
      run: swift --version

    - name: Build release binary
      run: swift build -c release

    - name: Make build script executable
      run: chmod +x build.sh

    - name: Create .app bundle
      run: ./build.sh

    - name: Create zip archive
      run: |
        zip -r LocalDash.zip LocalDash.app

    - name: Upload Release Asset
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} LocalDash.zip --clobber
